### ISSUE TITLE
How to access user inside policy?

### ISSUE THREAD

**Issue by notramo** [stephendolan/pundit#26]
The policy constructor accepts a user: `CommentPolicy.new(current_user)`, but the README doesn't contain an example of accessing it inside the policy.

**Comment by stephendolan** [comment]
Hi, @notramo! You can always check `ApplicationPolicy` for what you have access to. It depends on how you initialize it, but by default the variables available to you are `user` and `record`.

I've updated the `README.md` file with some better example content:
https://github.com/stephendolan/pundit/blob/main/README.md#creating-policies
