### ISSUE TITLE
How to access authorized resource inside the policy?

### ISSUE THREAD

**Issue by notramo** [stephendolan/pundit#27]
The `authorize` macro accepts a resource as parameter: `authorize(comment)`, however, there is no example in the README that shows how to access it inside the method, neither the equivalent generated code (as there is for `authorize` without arguments: `BookPolicy.new(current_user).index? || raise Pundit::NotAuthorizedError.new`).

**Comment by stephendolan** [comment]
Hi, @notramo! You can always check `ApplicationPolicy` for what you have access to. It depends on how you initialize it, but by default the variables available to you are `user` and `record`.

I've updated the `README.md` file with some better example content:
https://github.com/stephendolan/pundit/blob/main/README.md#creating-policies
