### ISSUE TITLE
Add support for Scopes in policies

### ISSUE THREAD

**Issue by robacarp** [stephendolan/pundit#7]
One of the nice features about Pundit is [scopes](https://github.com/varvet/pundit#scopes), though it creeps outside the "bare OO" simplicity model that Pundit espouses. Regardless, it's nice to be able to write one query enforcing scope everywhere. Has any thought been given to Scope objects here?

**Comment by stephendolan** [comment]
I definitely used scopes heavily in a few of my Rails projects where I included Pundit, and really enjoyed it.

That said, I'm not 100% sure on whether or not I'd want to create/maintain that functionality as a part of this shard. To your point, I quite like keeping this so dead simple that it's extremely easy to extend/contribute.

I have a feeling this will be one of those "Solve it when you need it" scenarios for me, lacking a PR with the functionality that I can review. It's much easier for me to wrap my head around the problem and solve it responsibly when I've got a production app I'm building with the need front and center 😄

**Comment by stephendolan** [comment]
Closing this for now, happy to accept/review a PR in the future, though.
